### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by XiaoYangon** [Vious/LBAM_Pytorch#5]
hello，I'm very sorry to disturb you. I use my data to train model, but Training process has a error：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 180, in run
    self._ev_writer.write_event(event)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 61, in write_event
    return self._write_serialized_event(event.SerializeToString())
  File "/usr/local/python3/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 65, in _write_serialized_event
    self._py_recordio_writer.write(event_str)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorboardX/record_writer.py", line 121, in write
    self._writer.flush()
OSError: [Errno 5] Input/output error
Do you have the same error？

**Comment by Carl-BoKai** [comment]
hello，I'm very sorry to disturb you. I use my data to train model, but Training process has a error：
ModuleNotFoundError: No module named 'tensorboardX.proto.summary_pb2'
how to deal this problem?
